version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    # runs as root
    user: '0'
    ports:
      - '3000:3000'
    # bindmount
    volumes:
      - './grafana_data:/var/lib/grafana'