version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    # runs as root
    user: '0'
    ports:
      - '3000:3000'
    # bindmount
    volumes:
      - './grafana_data:/var/lib/grafana'